// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuxYo23ccjBLGn_cozVOn-0phk8ehUcGE',
    appId: '1:461783993609:web:ad0c40c2b33b6b649717d8',
    messagingSenderId: '461783993609',
    projectId: 'flutter-gymapp-2cd4d',
    authDomain: 'flutter-gymapp-2cd4d.firebaseapp.com',
    storageBucket: 'flutter-gymapp-2cd4d.appspot.com',
    measurementId: 'G-DWDWGF8YTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGCouDei9EZivrqU65Xvraw2adi_vHmWI',
    appId: '1:461783993609:android:295a89d2df4d9a429717d8',
    messagingSenderId: '461783993609',
    projectId: 'flutter-gymapp-2cd4d',
    storageBucket: 'flutter-gymapp-2cd4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv7rmpSdcRbRL7FgvUb0CLCjbEtZ-EfTA',
    appId: '1:461783993609:ios:9cb840fbb329a1c89717d8',
    messagingSenderId: '461783993609',
    projectId: 'flutter-gymapp-2cd4d',
    storageBucket: 'flutter-gymapp-2cd4d.appspot.com',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv7rmpSdcRbRL7FgvUb0CLCjbEtZ-EfTA',
    appId: '1:461783993609:ios:b09b82e080348ded9717d8',
    messagingSenderId: '461783993609',
    projectId: 'flutter-gymapp-2cd4d',
    storageBucket: 'flutter-gymapp-2cd4d.appspot.com',
    iosBundleId: 'com.example.projeto.RunnerTests',
  );
}
